# Generated by Django 2.1.2 on 2018-10-31 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('formula', models.CharField(blank=True, max_length=500, null=True)),
                ('strunz_classification', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=500, null=True)),
                ('crystal_system', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_cell', models.CharField(blank=True, max_length=500, null=True)),
                ('crystal_symmetry', models.CharField(blank=True, max_length=500, null=True)),
                ('cleavage', models.CharField(blank=True, max_length=500, null=True)),
                ('mohs_scale_hardness', models.CharField(blank=True, max_length=500, null=True)),
                ('luster', models.CharField(blank=True, max_length=500, null=True)),
                ('streak', models.CharField(blank=True, max_length=500, null=True)),
                ('diaphaneity', models.CharField(blank=True, max_length=500, null=True)),
                ('optical_properties', models.CharField(blank=True, max_length=500, null=True)),
                ('refractive_index', models.CharField(blank=True, max_length=500, null=True)),
                ('crystal_habit', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_gravity', models.CharField(blank=True, max_length=500, null=True)),
                ('group', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
