# Generated by Django 2.1.4 on 2018-12-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181230_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verify',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
