# Generated by Django 2.1.4 on 2019-01-02 04:51

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181231_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar cropping'),
        ),
    ]
