# Generated by Django 2.1.4 on 2019-01-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190103_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_cropping',
        ),
    ]
